### PR TITLE
R-4.0 compatibility fix

### PR DESCRIPTION
**Pull request by ahonkela**
Potentially important compatibility fix for upcoming R-4.0. (Same bug in tigre caused vignette building to run indefinitely.)

I included minimal changes to NAMESPACE to make package check run without errors, but a lot of warnings remain that might be good to tackle.

### CODE REVIEW

**Review by alkalait — APPROVED** [review]
Thank you for taking care of this, Antti

**Comment by ahonkela** [comment]
Thanks Freddie!

Did you submit the new version to CRAN already?

**Comment by alkalait** [comment]
Not yet. The non trivial amount of inertia in relearning how to update on
CRAN will prevent from doing so at least until covid-19 blows over.

Stay safe

**Comment by ahonkela** [comment]
Is there something I can do to help? I am involved with other packages on CRAN and it did not seem too difficult then.

**Pull request merged**
